export const CLEANING = {
  DIV: "div",
  SPAN: "span",
  BUTTON: "button",
  H6: "h6",
  P: "p",
  CLEANING_AVATAR_IMAGE: 'img[alt="Curățenie"]',
  DROPDOWN_SELECT_WARD: '[data-test-id="selectInput-wards-select"] input:first-of-type',
  SELECTED_WARD: '[id^="react-select-7-option-"]',
  LOCATION_FIELD: "#react-select-8-placeholder",
  SELECTED_LOCATION: '[id^="react-select-8-option-0"]',
  LOCATION_OPTIONS: '[id^="react-select-8-option-"]',
  COMPLETED_LOCATION_FIELD: '[data-test-id^="option-"]',
  CLEANING_TYPE_FIELD: "#react-select-9-placeholder",
  SELECTED_CLEANING_TYPE: '[id^="react-select-9-option-"]',
  COMPLETED_CLEANING_TYPE_FIELD: '[data-test-id^="option-"]',
  SUBSTANCE_FIELD: "#react-select-10-placeholder",
  SELECTED_SUBSTANCE: '[id^="react-select-10-option-"]',
  COMPLETED_SUBSTANCE_TYPE_FIELD: '[data-test-id^="option-"]',
  TIMELAPSE_ICON: '[data-testid="TimelapseIcon"]',
  CORRECTIVE_ACTION_FIELD: 'input[placeholder="Selectează pas/acțiune"]',
  CORRECTIVE_ACTION_OPTIONS: '[role="option"]',
  CHECKBOX: '[type="checkbox"]',
};
