export const STERILIZATION = {
    STERILIZATION_AVATAR_IMAGE: 'img[alt="Sterilizare"]',
    DIV: 'div',
    LABEL: 'label',
    DROPDOWN_SELECT_WARD: "#react-select-4-placeholder",
    BUTTON: "button",
    SPAN: "span",
    P: "p",
    EDIT_ICON: '[data-testid="EditIcon"]',
    DELETE_ICON: '[data-testid="DeleteIcon"]',
    SELECTED_WARD: '[id^="react-select-4-option-"]',
    CONCENTRATION: 'input[placeholder="Selecteză concentrația"]',
    COMPLETED_WARD_FIELD: '#react-select-5-value-container, .custom-select__single-value',
    ASSET_CATEGORY_FIELD: '#react-select-5-placeholder',
    ASSET_CATEGORY_OPTION: '[id^="react-select-5-option-"]',
    SELECTED_ASSET: '#react-select-5-value-container, .custom-select__single-value',
    CHECKBOX_RECEPTION: 'input.PrivateSwitchBase-input[type="checkbox"]',
    SUBSTANCE_FIELD: '#react-select-16-placeholder',
    SUBSTANCE_OPTION: '[id^="react-select-16-option-"]',
    CONCENTRATION_FIELD: 'input[placeholder="Selecteză concentrația"]',
    CONCENTRATION_OPTION: 'ul[role="listbox"] li',
    DISINFECTION_SUBSTANCE_FIELD: '#react-select-22-placeholder',
    DISINFECTION_SUBSTANCE_OPTION: '[id^="react-select-22-option-"]',
    STERILIZATION_CYCLE_NR: 'input[placeholder="Numărul ciclului"]',
    TEMPERATURE_FIELD_CYCLE: 'input[placeholder="Alege temperatura"]',
    PRESSURE_FIELD_CYCLE: 'input[placeholder="Alege presiunea"]',
    COMMENTS_FIELD_CHECK_FUNCTIONALITY: '[data-field-id="sterilization_functionality_textarea"]',
    PACKING_SET_NUMBER_FIELD: 'input[data-field-id="sterilization_packing_set_number',
    MARKER_FIELD: '#react-select-28-input',
    MARKER_OPTION: '[id^="react-select-28-option-"]',
    SELECTED_TEXT_MARKER_FIELD: '#react-select-28-value-container, .custom-select__single-value',
    STERILIZATION_DEVICE_SCHEDULING: '#react-select-34-placeholder',
    STERILIZATION_DEVICE_SCHEDULING_OPTION: '[id^="react-select-34-option-"]',
    STERILIZATION_DEVICE_SCHEDULING_SELECTED_TEXT: '#react-select-34-value-container, .custom-select__single-value',
    MARKER_PENDING_CYCLES_FIELD: '[id^="react-select-38-placeholder"]',
    MARKER_PENDING_CYCLES_OPTION: '#react-select-38-listbox div',
    MARKER_PENDING_CYCLES_SELECTED_TEXT: '[data-test-id^="option-markers-select"]',
    SUCCESS_MESSAGE_MODAL: '#client-snackbar',
    ARROW_ICON: '[data-testid="ArrowForwardIosRoundedIcon"]',
    CONFORMITY_RADIO_BUTTON_TRUE: 'input[type="radio"][value="true"]',
    ARROW_ICON_BUTTON: '[data-testid="ArrowForwardIosRoundedIcon"]'
}